- cmd/main.go
- cmd/upgrade/cmd.go
- cmd/upgrade/internal/powershell/powershell.go
- cmd/upgrade/upgrade.go
This PR adds support for running `.\wins up[grade]`, which runs a Powershell script within wins that restarts the service with a different wins server binary.
This is an alternative to the current mechanism for upgrades that wins provides wherein it watches for a path and utilizes checksums to see whether the service should be modified / restarted and can also be used as an alternative method to enable wins on a Windows host (e.g. you can just run `.\wins up` instead of `.\wins srv app run --register; Start-Service -Name rancher-wins`).
The primary use case of this feature is to support a new Helm chart that will allow users to maintain wins configs / wins versions across entire clusters using just a Helm chart for configuration. This Helm chart uses wins (cli) to pass wins (upgrade) to …
> Add wins up[grade]

- charts/rancher-wins-upgrader/scripts/upgrade.ps1
- charts/rancher-wins-upgrader/templates/daemonset.yaml
The reason why this change is necessary is because wins performs a checksum on the exact same path that must exist in the container and must exist on the host. Therefore, even though there is no need for the container to have knowledge of the CATTLE_PREFIX_PATH, it must for wins to be able to checksum correctly.
Related Issue: https://github.com/rancher/rancher/issues/32194
> Put binary in prefixPath within container

- install.ps1
This just copies the wins.exe as part of the instal.ps1 to guarantee that Wins in the location expected in the charts. This was handled by the Rancher-agent prior to RKE2.
* https://github.com/rancher/rancher/issues/35851
> Copying the wins.exe to the location expected by monitoring chart.

- install.ps1
This is to enable the ability to configure CSI Proxy leveraging Rancher.
* https://github.com/rancher/windows/issues/114
> Adding the ability to configure the CSI Proxy in the installation script

- pkg/paths/file.go
problem: wins uses a copy of the file you want to use with the `cli prc` command. it makes a copy of that file in a local working dir to make sure it has it's own version. if you restart a pod once it will see the copied file there and move to temp to keep a backup. you restart a pod a second time it will not delete the file in TEMP, just move the file again and fail when it exists.
fix: no one really seems to need the copy so we're opting to delete it if it's already there to just let wins move on and bring in the copied exe again.
> switch to deleting the existing file instead of moving it to temp dir

- pkg/syscalls/route.go
fixes regression introduced in #54. sycalls are case-sensitive.
Error log:
```
PS C:\Users\capi> wins cli net get
time="2022-03-23T13:55:41Z" level=fatal msg="rpc error: code = Unknown desc = panic Failed to find GetIPForwardTable procedure in iphlpapi.dll: The specified procedure could not be found."
```
minimal repro:
```golang
package main
import (
"fmt"
"syscall"
"unsafe"
)
type IPForwardTable struct {
NumEntries uint32
Table      [1]IPForwardRow
}
type IPForwardRow struct {
ForwardDest      uint32
ForwardMask      uint32
ForwardPolicy    uint32
ForwardNextHop   uint32
ForwardIfIndex   uint32
ForwardType      uint32
ForwardProto     uint32
ForwardAge       uint32
ForwardNextHopAS uint32
ForwardMetric1   uint32
ForwardMetric2   uint32
ForwardMetric3   uint32
ForwardMetric4   uint32 …
```
> fix: casing for windows syscalls

- README.md
csi-proxy did not support 2022 until v1.1.1 per https://github.com/kubernetes-csi/csi-proxy/commit/2a1dfdb670b6e8efbc987b6347e59dbcea35c97d
This was not documented or mentioned in a release-note in the csi-proxy repo
> bump version of csi-proxy in README to support Windows Server 2022

- README.md
- cmd/server/config/config.go
- pkg/csiproxy/csi.go
- pkg/defaults/variable.go
- pkg/tls/tls.go
add new functionality for fetching certificates from Rancher, external URL, and from a local file.
> Add TLS and CA Certificate support for wins

- cmd/cmds/tools.go
- cmd/server/config/config.go
- pkg/csiproxy/csi.go
- pkg/profilings/stack.go
- pkg/tls/tls.go
I created an import cycle in my last PR, this fixes it and also addresses feedback from QA that the informational stackdump message logged once the wins server has started up does not indicate that it is informational.
> fix import cycle, enhance stackdump info message

- cmd/server/config/config.go
- install.ps1
- pkg/csiproxy/csi.go
- pkg/tls/tls.go
This fixes an issue where the install script was over-riding existing wins config as well as sets the default csiProxy http transport to be insecure.
Fixes a new bug found while testing https://github.com/rancher/rancher/issues/36732 and https://github.com/rancher/rancher/issues/36574
- do not override the wins config when using the wins install script
- ensure that the default certFilePath in wins config is empty for non-rancher users
- set certFilePath as part of the wins install script
- call ValidateTLSConfig as part of wins config validation
- default to using an insecure http transport to match system-agent functionality
in csi.go, we are now specifying an http.Transport struct as it is the only way to mimic a `--insecure` that is used in the system-agent scripts.
I tested the …
> fix tlsConfig for csi proxy and install script

- .github/pull_request_template.md
- cmd/server/config/config.go
- install.ps1
- Addresses bug found during testing for https://github.com/rancher/rancher/issues/37628
- Fixes an issue where the `certFilePath` was set in the wins installation script without checking if the file path was valid and a certificate was required
- check if tls-config is valid/present before setting certFilePath
By moving the tls-config logic in the install script behind an `if (Test-Path -Path $env:RANCHER_CERT) -and ($env:CA_REQUIRED -eq "true")`, this ensures that wins will only set the tls-config if the requirements are met.
standard installation of wins (system-agent for Windows) via the install script.
No regressions are expected.
Unavailable.
> check if tls-config is valid/present before setting certFilePath + add PR tempate

- install.ps1
Fixes an issue in https://github.com/rancher/rancher/issues/36574
Fixes an issue in https://github.com/rancher/rancher/issues/36732
the wins install script will now set the proper proxy registry keys if the environment proxy variables are detected.
in the system-agent implementation of wins, using a proxy was not working as expected due to the registry values not being set for the proxy. This is a change 
installation of windows worker nodes via system-agent (wins) behind a proxy
none, as this functionality is currently broken.
> set windows registry values for proxy

- pkg/csiproxy/csi.go
Fixes https://github.com/rancher/rancher/issues/36574
Ensure that we attempt to load proxy configuration from environment variables when downloading the csi-proxy tarball.
`ProxyFromEnvironment` is supposed to work the same on both Linux and Windows per https://pkg.go.dev/net/http#ProxyFromEnvironment
Any use-cases involving a proxy to reach internal/external network addresses
No regressions should occur.
> read proxy config from env vars for csi-proxy download

- .drone.yml
We are having an issue with the github binary release plugin for drone. The documentation is lacking on the drone side and due to this being a release blocker, I have opted for a faster path of using a temporary volume
> use temp volume to persist binary from publish step

- suc/run.ps1
Fixes https://github.com/rancher/rancher/issues/38896 and https://github.com/rancher/rancher/issues/38915
A change was made in PR https://github.com/rancher/wins/pull/141 that changed logs to being written to both the EventLog and host. The issue with this is that the EventLog didn't exist within the container, and rather than attempt to create the containerized EventLog, it's probably easier to just write logs to the host. 
This PR retains the increased log verbosity but does not attempt to write to the EventLog anymore.
We should make sure the SUC image still works.
The SUC image.
> Revert EventLog support for SUC script back to Write-Host

- .drone.yml
For some strange reason `go get github.com/onsi/gomega/...` works in Drone-PR for both Win versions (https://drone-pr.rancher.io/rancher/wins/393) and in Drone-Publish for Win2022 (https://drone-publish.rancher.io/rancher/wins/182/2/2), but fails in Drone-Publish for Win1809 (https://drone-publish.rancher.io/rancher/wins/182/1/2). This PR is removing that dependency from the build pipeline which apparently is not needed.
```
go get github.com/onsi/gomega/...
go: go.mod file not found in current directory or any parent directory.
'go get' is no longer supported outside a module.
To build and install a command, use 'go install' with a version,
like 'go install example.com/cmd@latest'
For more information, see https://golang.org/doc/go-get-install-deprecation
or run 'go help get' or 'go help …
```
> Fix pipeline by removing `github.com/onsi/gomega`

- .drone.yml
- README.md
- go.mod
- magefiles/magefile.go
- tests/integration/docker/Dockerfile.wins-cli
- tests/integration/docker/Dockerfile.wins-nginx
- tests/integration/docker/Dockerfile.wins-upgrade
- tests/integration/integration_suite_test.ps1
+ Update `README.md` to remove references to old powershell scripts which are no longer used 
+ Update `MAINTAINERS` in drone.yml
+ Add new mage build targets so integration tests can be manually run  
+ Integration tests are not run in drone, only unit tests are 
+ A prior PR completely removed scripts / targets needed to run the integration tests during the transition to using mage files, but did not reintroduce a target for the integration tests
+ Update copyright date 
+ coalesce go.mod requirement blocks
If theres some context that I've missed surrounding the changes made to the integration tests let me know, from what I could tell they were in a state of limbo after the departure of Ross and Jamie and felt that adding them back would be useful for local development
> Update Maintainers, Add Integration Target, Update README

- install.ps1
Issue: https://github.com/rancher/rancher/issues/43587
When obtaining Rancher connection information wins is not specifying a desired node-name. This means that users cannot set custom node names when creating windows nodes within Rancher. The `v3/connect/agent` endpoint uses the `X-Cattle-Node-Name` header to specify what name an incoming node should use, and the current `install.ps1` script does not use that header.
Adding windows workers to custom clusters using custom node names, as well as adding windows nodes to custom clusters without specifying a custom node name
Adding this additional header should not introduce any potential regressions. Dev testing has shown that this change does not negatively impact node registration when a custom node name is **not** used. 
Scenarios where …
> Pass X-Cattle-Node-Name header when generating connection info

- install.ps1
The missing environment variables `https_proxy` and `no_proxy` appear in the value of the environment variable `http_proxy`.
The environment variables `http_proxy`, `https_proxy`, and `no_proxy` are all correctly set.
I use [Sysinternals Process Explorer](https://learn.microsoft.com/en-us/sysinternals/downloads/process-explorer) to check environment variables of the `wins.exe` windows process.
- Edition: `Windows Server 2022 Standard`
- Version: `21H2`
- OS build: `20348.2113`
The following example are from official doc. It shows that the value of `MultiString` can be `an array of values`.
> ### Example 4: Create a MultiString value in the registry using an array
>
>The example shows how to use an array of values to create the MultiString value.
>
>```powershell
>$newValue = …
```
> Fix issues related to powershell commands and regedit when using a proxy

- go.mod
Addresses
https://github.com/rancher/rancher/issues/45325
Bumped go version from 1.18 to 1.21
While the `go.mod` file format changed due to the bump, no version changes have occurred in any dependencies
Once a new wins version is released and bumped in Rancher, provision a custom windows cluster on RKE2
n/a
> Bump to go 1.21

- .github/workflows/release.yaml
The Prior PR for GHA migration did not use the proper path when accessing vault credentials, as such the release stage is not producing the correct artifacts. This was not caught in testing, as the vault integration can only be used once it has been merged into a Rancher repo.
> [GHA] Update vault URL

- install.ps1
Issue https://github.com/rancher/rancher/issues/47039
In the event that the install script is run multiple times, the `rancher-wins` config (located at `/etc/rancher/wins/config`) will be continuously appended to. `rancher-wins` is able to handle this case, as the yaml marshaling dependency we use (`github.com/ghodss/yaml`) seems to only consider the last instance of the duplicate fields in the config file (This behavior can be confirmed by executing this go playground https://go.dev/play/p/-yV1GJSQDd-). For this reason, this duplication does not negatively impact any functionality. However, this behavior is messy and does not match the linux system-agent-install script behavior. Ideally, there should be no duplicates in the config file no matter how many times the install script is ran. …
> Overwrite the config file during installation if needed

- .github/workflows/PR.yaml
- .golangci.json
- magefiles/magefile.go
- suc/pkg/cmd.go
- suc/pkg/host/common.go
- suc/pkg/host/common_test.go
- suc/pkg/host/embed.go
- suc/pkg/host/upgrade.go
- suc/pkg/service/service.go
- suc/pkg/state/state.go
- tests/integration/install_test.ps1
- tests/integration/suc_test.ps1
- tests/integration/suc_upgrade_test.ps1
- tests/integration/utils.psm1
Issue: https://github.com/rancher/rancher/issues/47652
The `rancher-wins` system-upgrade-controller image does not automatically upgrade the `wins.exe` binary on the host. This forces users to reprovision Windows nodes in order to obtain the latest version of the `system-agent` and `rancher-wins`, and has resulted in unnecessary changes in Rancher to handle behavior differences between different versions of `rancher-wins`. 
This PR introduces a new `host` package which embeds the latest version of `wins.exe` into the SUC image during compilation. When the SUC image runs, it will compare the version of wins installed onto the host (by invoking `c:\Windows\wins.exe --version`) and, if needed, write the embedded version to disk into the required directories (`c:\Windows` & …
> Implement auto upgrades of wins.exe via the SUC image

- suc/pkg/cmd.go
- suc/pkg/service/configure.go
- suc/pkg/service/service_rancher_wins.go
- suc/pkg/service/state/state.go
- tests/integration/suc_test.ps1
- tests/integration/utils.psm1
Moving forward, all `v0.4.x` releases of rancher-wins are intended to be used by Rancher <= v2.9.x.
Unfortunately, a feature for Rancher v2.10 and above was included in rancher-wins `v0.4.20`. ideally this would have been tagged at `v0.5.0`. This PR removes the core logic for that feature from the `v0.4` release line, while maintaining some of the enhancements regarding restarting the `rancher-wins` service when set as a dependency on the `rke2` service.
> [v0.4] Remove support for service configuration via the SUC

- .github/workflows/merge.yaml
- go.mod
- go.sum
Replaces the `inet.af/tcpproxy` dependency with the mirrored github repo `github.com/inetaf/tcpproxy`. As explained [in the upstream issue](https://github.com/inetaf/tcpproxy/issues/39), the `.af` TLD is no longer trustworthy and should not be used.  
Add `inet.af/tcpproxy => github.com/inetaf/tcpproxy v0.0.0-20240214030015-3ce58045626c` to `go.mod`. This also bumps the commit used, however the only new changes present are located in the `README.md` file and `go.mod` file.
Also updated the merge CI for GHA, as it did not match the PR flow and was failing. 
The client proxy package which uses this dependency is not currently used in the rke2 provisioning process, and afaik was only used in rke1 provisioning (which has been EOL for some time now). We may want to consider removing the proxy …
> [0.5] `inet.af/tcpproxy` -> `github.com/inetaf/tcpproxy`

- .github/workflows/release.yaml
A recent attempt to release a new rc for v0.5.1 resulted in [CI failures](https://github.com/rancher/wins/actions/runs/14223599350/job/39857537663), specifically errors such as the below are seen 
```
Error: level=error msg="[linters_context] typechecking error: D:\\a\\wins\\wins\\cmd\\cmds\\tools.go:12:29: undefined: cli"
```
This is a similar issue to what was seen in PR CI, which was resolved by bumping `golangci-lint` to a more recent version and removing the standalone github action step. I was able to [reproduce this same error in my personal fork](https://github.com/HarrisonWAffel/wins/actions/runs/14225030450/job/39862388596), and was also able to [confirm this fix in my fork](https://github.com/HarrisonWAffel/wins/actions/runs/14224699009/job/39861249988) …
> [main] Fix release CI

- .github/workflows/PR.yaml
- .github/workflows/merge.yaml
- .github/workflows/release.yaml
- tests/integration/integration_suite_test.ps1
Github is removing support for the Windows 2019 runner on June 30th, but Rancher has not dropped 2019 support. In order to continue supporting Windows provisioning for 2019, the rancher-wins CI needs to be updated to build the 2019 SUC image without using any 2019 runners. This can be done by using Windows 2025, which is able to build 2019 and 2022 images as long as no `RUN` statements are present. 
This PR updates the CI to build 2019 on 2025, as well as short circuits some integration tests from running on 2025. These tests do not cover any functionality currently used by Rancher provisioning, and will still run on 2022, so we aren't losing any relevant test coverage. 
Once this PR is merged it will be backported to 0.4 branch. 
These CI changes were tested locally
Passing PR Run: …
> 2019 GHA Removal

- go.mod
- go.sum
- install.ps1
- pkg/csiproxy/csi.go
- tests/integration/install_certs_test.ps1
- tests/integration/install_test.ps1
- tests/integration/utils.psm1
Issue: https://github.com/rancher/rancher/issues/47758
During node registration `install.ps1` will contact the local Rancher server `/cacerts` endpoint so that it can add any custom CA and intermediate certificates into the Windows certificate store. Importing the certificates into the Windows store ensures that all applications on the host can properly communicate with the Rancher server, and is required for the later portions of `install.ps1` to function as expected.
Currently, the install script simply runs `Import-Certificate` against a file containing the response body of the `/cacerts` endpoint. Unfortunately, `Import-Certificate` will only ever import a single certificate, even if multiple are included in the provided file. Due to this, Windows nodes do not properly handle private …
> fix: Properly handle certificate chains in install.ps1
