.drone.yml
charts/rancher-wins-upgrader/.helmignore
charts/rancher-wins-upgrader/Chart.yaml
charts/rancher-wins-upgrader/README.md
charts/rancher-wins-upgrader/app-readme.md
charts/rancher-wins-upgrader/scripts/noop.ps1
charts/rancher-wins-upgrader/scripts/upgrade.ps1
charts/rancher-wins-upgrader/templates/_helpers.tpl
charts/rancher-wins-upgrader/templates/configmap.yaml
charts/rancher-wins-upgrader/templates/daemonset.yaml
charts/rancher-wins-upgrader/templates/rbac.yaml
charts/rancher-wins-upgrader/values.yaml

Related Issue: https://github.com/rancher/wins/issues/20

Add wins-upgrader chart

---

charts/rancher-wins-upgrader/templates/_helpers.tpl
charts/rancher-wins-upgrader/values.yaml

Related Issue: https://github.com/rancher/rancher/issues/32194

Default to c:/ for rkeWindowsPathPrefix if unset

---

charts/rancher-wins-upgrader/README.md
charts/rancher-wins-upgrader/scripts/upgrade.ps1
charts/rancher-wins-upgrader/templates/_helpers.tpl
charts/rancher-wins-upgrader/templates/configmap.yaml
charts/rancher-wins-upgrader/templates/daemonset.yaml
charts/rancher-wins-upgrader/values.yaml

Related Issue: https://github.com/rancher/rancher/issues/32194

Use C:\\ for default prefixPath and allow backslashes

---

scripts/build.ps1
scripts/entry.ps1
scripts/integration.ps1
scripts/release.ps1
scripts/test.ps1
scripts/utils.psm1
scripts/version.ps1
tests/integration/application_test.ps1
tests/integration/hns.psm1
tests/integration/hns_test.ps1
tests/integration/host_test.ps1
tests/integration/integration_suite_test.ps1
tests/integration/network_test.ps1
tests/integration/process_test.ps1
tests/integration/route_test.ps1
tests/integration/utils.psm1

We have discussed a style guide for PowerShell so we are bringing these inline with MS standards.

Formatting PowerShell scripts to match our style guide.

---

.drone.yml

adds fossa scanning to the 1809 build process after the build
https://github.com/rancherlabs/eio/issues/504

adding fossa step to 1809

---

install.ps1

Rancher needs a very specific configuration when using Wins as an agent. This installation script handles that configuration and setup.
Signed-off-by: Jamie Phillips  <jamie.phillips@suse.com>

Installation script for Rancher

---

.drone.yml
manifest.tmpl
scripts/package.ps1
scripts/version.ps1
tests/integration/integration_suite_test.ps1

Linked Issues:
* https://github.com/rancher/windows/issues/104

Adding Windows Server 2022 support.

---

docs/adrs/0004-csi-proxy-and-configuration.md

This PR is for the proposed architecture decision for CSI Proxy and to enable the discussion.

ADR for CSI Proxy

---

.gitignore
.goreleaser.yml
README.md
cmd/server/app/run.go
cmd/server/config/config.go
pkg/csiproxy/csi.go
pkg/systemagent/agent.go

Adding CSI Proxy support and adding goreleaser functionality to help with cross-platform builds.
* https://github.com/rancher/windows/issues/114

Adding CSI Proxy support and goreleaser

---

.github/workflows/main.yml

Created based on https://docs.github.com/en/actions/managing-issues-and-pull-requests/adding-labels-to-issues

Create label-opened-issues.yml to add team label to any issues opened

---

pkg/concierge/concierge.go

This needed to be cleaned up correctly so added better handling.
Tested and verified to be working as expected.

Improving the service handling code in concierge.

---

charts/rancher-wins-upgrader/Chart.yaml

Adds the annotation per this issue.
* https://github.com/rancher/rancher/issues/36401

Adding permits-os annotation to wins-upgrader chart.

---

install.ps1

There was an issue with how the switch statements for checking curl results were being processed.
* https://github.com/rancher/windows/issues/151

Improving the curl switch handling.

---

go.mod
go.sum

a lot of changes went into system agent for rancher v2.6.4, pinning latest version of system-agent for feature parity.

pin v0.2.0 of system-agent

---

install.ps1

PowerShell 5.1, the default on Windows Server, doesn't support consuming the environment variables for proxy configuration. This is fixed in newer versions but want to be backported. Another issue occurred that wasn't saving these to the registry correctly for wins.
Switched to using curl instead of Invoke-RestMethod and made a change to how the registry key was getting edited/added.
Installation of a cluster from Rancher.
Installation of a Windows node using the command from Rancher.
Configure a system using a proxy and set the agent vars in Rancher when creating the cluster. 
* https://github.com/rancher/rancher/issues/36732

Correcting issues related to proxy for PowerShell commands and regedit

---

.drone.yml

https://github.com/rancher/wins/issues/97

switch to drone-fossa-plugin

---

go.mod
go.sum

https://github.com/rancher/wins/pull/96

pin v1.20.0 of urfave for a args parsing error with double quotes

---

uninstall.ps1

This is a PowerShell script for cleaning up the Wins agent installation. It will also uninstall RKE2 if installed.
This is for issues:
* https://github.com/rancher/windows/issues/171
* https://github.com/rancher/rancher/issues/37283

Creating an uninstall script for the Wins agent.

---

.gitignore
pkg/concierge/concierge.go
pkg/profilings/dump.go

should fix an issue with dirty repo during build process

go fmt and gitignore additions

---

README.md
install.ps1

the conversion to yaml from json added a typo bug that didn't like the whitelists get unmarshalled properly.
https://github.com/rancher/rancher/issues/37022

fixing white_list

---

go.mod
go.sum

https://github.com/rancher/rancher/issues/37628

pin sa v0.2.7

---

package/windows/Dockerfile
scripts/package.ps1
suc/run.ps1

The script supports traditional way that wins can upgrade itself and
host process containers.

Created system-upgrade-controller image and script.

---

.drone.yml

hardcode binary location

---

Dockerfile
make.ps1
scripts/build.ps1
scripts/ci.ps1
scripts/package.ps1

Fixes an issue where backwards compatibility for wins binary locations was not considered with the changes I made when removing dapper
- begin using `ContainerAdministrator` for the wins image

proper packaging in final multi-stage build step

---

.dockerignore
.drone.yml
Dockerfile
make.ps1

attempting to fix an issue with drone plugin for the github binary release failing for unknown reasons

manual docker cp step

---

.drone.yml

Needed to tweak the binary release task again.

---

go.mod
go.sum

Updating the system agent to pull in a fix for TLS cert handling on Windows.

Updating system agent.

---

.dockerignore
.drone.yml
.gitignore
go.mod
go.sum
magefiles/magefile.go
magetools/gotool.go

Fixes https://github.com/rancher/rancher/issues/38650
fixes an issue with previous releases where the version was considered `dirty`

fix dirty repo in drone CI

---

suc/run.ps1

Fixes https://github.com/rancher/rancher/issues/38646
- Improves logging for the powershell script run as part of suc on windows 
- now writes out the logs from the wins container to the rancher-wins event log source in the application log
- addresses a bug where the system-agent upgrade on windows was working but reporting an unexpected error message that caused it to incorrectly report as a failure (an error is expected but not the one seen)

improve logic and logging

---

go.mod
go.sum

go mod download should fix the dirty repo

go mod download to fix dirty repo

---

go.mod
go.sum

Bump system-agent for rancher/rancher#39066

Bump system-agent

---

go.mod
go.sum

https://github.com/rancher/rancher/issues/39066

Update system-agent to v0.2.12

---

.drone.yml

No real changes. Simple change to Drone file to mirror the workaround in rancher/rancher:
https://github.com/rancher/rancher/blob/58bfcb19605d51bf24f0aa5bf1d60a68b1ae2a27/.drone.yml#L948-L951

Fix pipeline failures

---

magefiles/magefile.go

VEX related improvements in the build process
